name: Build Unity game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL
          - Android
          - iOS
          - StandaloneOSX
          - StandaloneLinux64
        unityVersion:
          - 2019.4.5f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unity Builder
        uses: game-ci/unity-builder@v4.0.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Frog-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  build-on-windows:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      matrix:
        targetPlatform:
          - WSAPlayer
          - tvOS
        unityVersion:
          - 2019.4.5f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unity Builder
        uses: game-ci/unity-builder@v4.0.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Frog-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
