name: Test Unity

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE2 }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: unity-test-results
          path: artifacts
