name: Build Unity game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - WebGL
          - Android
          - iOS
          - StandaloneOSX
          - StandaloneLinux64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unity Builder
        uses: game-ci/unity-builder@v4.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Frog-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  build-on-windows:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: windows-2022
    strategy:
      matrix:
        targetPlatform:
          - WSAPlayer
          - tvOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unity Builder
        uses: game-ci/unity-builder@v4.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Frog-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
