name: Build Unity

on: [push, pull_request]

jobs:
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: game-ci/unity-builder@v3.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE2 }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: Frog-Windows
          path: build

  build-webgl:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: game-ci/unity-builder@v3.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE2 }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: Frog-WebGL
          path: build
